# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vimo's Blog
description: > # this means to ignore newlines until "baseurl:"
  Material theme based on <a href="http://materializecss.com">Materialize.css</a> for jekyll sites
baseurl: ""
url: "http://blog.vimo.cloud"
permalink: /:year/:month/:day/:title
repository: lsw1991abc/lsw1991abc.github.io
paginate: 5

# specific configurations
github_profile: "https://github.com/lsw1991abc"
user: "Wizard"
user_email: "lsw1991abc@gmail.com"
contact_url: "http://blog.vimo.cloud"
#google_tracking_id: ""
#google_site_verification: ""
#disqus_shortname: ""

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
